#!/usr/bin/env bash 

if [ "$ACTION" == "enable" ]; then
  if [ "$ROOT" == "true" ]; then
    systemctl daemon-reload
    sleep 2
    systemctl enable "${SERVICE}" --now
    sleep 2
    if ! systemctl is-active --quiet "${SERVICE}"; then
      exit 1
    fi
  else
    systemctl --user daemon-reload
    sleep 2
    systemctl --user enable "${SERVICE}" --now
    sleep 2
    if ! systemctl --user is-active --quiet "${SERVICE}"; then
      exit 1
    fi
  fi
fi

if [ "$ACTION" == "restart" ]; then
  if [ "$ROOT" == "true" ]; then
    systemctl daemon-reload
    sleep 2
    systemctl stop "${SERVICE}"
    sleep 2
    systemctl start "${SERVICE}"
    sleep 2
    if ! systemctl is-active --quiet "${SERVICE}"; then
      exit 1
    fi
  else
    systemctl --user daemon-reload
    sleep 2
    systemctl --user stop "${SERVICE}"
    sleep 2
    systemctl --user start "${SERVICE}"
    sleep 2
    if ! systemctl is-active --quiet "${SERVICE}"; then
      exit 1
    fi
  fi
fi

if [ "$ACTION" == "stop" ]; then
  if [ "$ROOT" == "true" ]; then
    systemctl stop "${SERVICE}" && rm -rf /etc/systemd/system/"${SERVICE}"
  else
    systemctl --user stop "${SERVICE}" && rm -rf /etc/systemd/system/"${SERVICE}"
  fi
fi
