volume: fetchit-volume # this needs to match the volume name passed to the podman run command
targets:
- name: fetchit
  url: http://github.com/redhat-et/fetchit
  methods:
    fileTransfer:
      targetPath: examples/filetransfer/
      destinationDirectory: /tmp/ft
      schedule: "*/1 * * * *"
  branch: ci
