volume: harpoon-volume # this needs to match the volume name passed to the podman run command
targets:
- name: harpoon
  url: http://github.com/redhat-et/harpoon
  methods:
    clean:
      All: true
      Volumes: true
      schedule: "*/1 * * * *"
  branch: main
