# This is an example configReload that is used in testing. Fetchit will start with this config then will load targetConfigs from ./examples/config-reload.yaml
# Note: It takes (default) 5 min for raw urls to be updated in GitHub, so this test will wait for 7 min
configReload:
  configURL: https://raw.githubusercontent.com/containers/fetchit/main/examples/config-reload.yaml
  schedule: "*/1 * * * *"
