# for this test, start with this config, then wait to be sure the
# targets from .fetchit/config.yaml are populated
# and for follow-up test, push a change to the config and confirm
# new targets are fetched & run
configTarget:
  configURL: https://raw.githubusercontent.com/josephsawaya/fetchit/better-apply/examples/config-reload.yaml
  schedule: "*/2 * * * *"
targets:
- name: fetchit
  url: https://github.com/containers/fetchit
  raw:
  - name: raw-ex
    targetPath: examples/raw/
    schedule: "*/1 * * * *"
    pullImage: false
  branch: main
