# for this test, start with this config, then wait to be sure the
# targets from .fetchit/config.yaml are populated
# and for follow-up test, push a change to the config and confirm
# new targets are fetched & run
targets:
- name: fetchit
  url: https://github.com/containers/fetchit
  methods:
    configTarget:
      configUrl: https://raw.githubusercontent.com/josephsawaya/fetchit/better-apply/examples/config-reload-with-skew.yaml
      schedule: "*/2 * * * *"
    raw:
      targetPath: examples/raw/
      schedule: "*/1 * * * *"
      pullImage: false
      skew: 5000
  branch: main
