targetConfigs:
- url: https://github.com/josephsawaya/fetchit
  raw:
  - name: raw-ex
    targetPath: examples/raw
    glob: "*.json"
    schedule: "*/1 * * * *"
    pullImage: false
  branch: fix-target-path
