targetConfigs:
- name: fetchit
  url: https://github.com/cooktheryan/fetchit
  image:
  - name: httpd-ex
    url: http://localhost:8080/httpd.tar
    schedule: "*/1 * * * *"
  raw:
  - name: raw-ex
    targetPath: examples/imageLoad/
    schedule: "*/1 * * * *"
    pullImage: false
  branch: imageWNewMeth
