volume: new-volume # this needs to match the volume name passed to the podman run command
repos:
- name: harpoon
  target:
    url: http://github.com/redhat-et/harpoon
    kube: 
      subdirectory: examples/kube
      schedule: "*/1 * * * *"
    branch: main
