volume: new-volume # this needs to match the volume name passed to the podman run command
targetConfigs:
- name: fetchit
  url: http://github.com/containers/fetchit
  kube:
  - name: kube-ex
    targetPath: examples/kube/
    schedule: "*/1 * * * *"
  branch: main
