targetConfigs:
- name: fetchit
  url: http://github.com/containers/fetchit
  systemd:
  - name: sysd-ex
    targetPath: examples/systemd/httpd.service
    root: true
    enable: false
    schedule: "*/1 * * * *"
  branch: main
