volume: harpoon-volume # this needs to match the volume name passed to the podman run command
repos:
- name: harpoon
  target:
    url: http://github.com/redhat-et/harpoon
    systemd:
      subdirectory: examples/systemd/httpd.service
      user: root
      schedule: "*/1 * * * *"
    branch: main
