apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - name: nginx-server
    image: quay.io/fetchit/fetchit-sample-app:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
      hostPort: 8080
    volumeMounts:
        - mountPath: "/var/www/html"
          name: task-pv-storage
