apiVersion: v1
kind: ConfigMap
metadata:
  name: env
data:
  APP_COLOR: red 
  tree: trunk
---
apiVersion: v1
kind: Pod
metadata:
  name: colors
spec:
  containers:
  - name: colors
    image: docker.io/mmumshad/simple-webapp-color:latest
    ports:
    - containerPort: 8080
      hostPort: 8080
    envFrom:
    - configMapRef:
        name: env
        optional: false
