name: Build and Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CGO_ENABLED: 0
  PODMAN_VER: v4.1.1

jobs:
  build-fetchit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        run: sudo apt install curl
      
      - name: Build the image
        run: go mod tidy -compat=1.17 && go mod vendor && docker build . --file Dockerfile --tag quay.io/fetchit/fetchit-amd:latest
    
      - name: Export image
        run: docker save -o /tmp/fetchit.tar quay.io/fetchit/fetchit-amd:latest

      - name: Save container as artifact
        uses: actions/upload-artifact@v1
        with:
          name: fetchit-image
          path: /tmp/fetchit.tar

  scan-fetchit-sbom:
    runs-on: ubuntu-latest
    needs: [build-fetchit]
    steps:
      - name: Download fetchit image
        uses: actions/download-artifact@v1
        with:
          name: fetchit-image
          path: /tmp

      - name: load images
        run: podman load -i /tmp/fetchit.tar

      - name: Run Trivy vulnerability scanner against FetchIt
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: quay.io/fetchit/fetchit-amd:latest
          format: 'github'
          output: 'dependency-results.sbom.json'
          exit-code: '1'
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'