name: Build and Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CGO_ENABLED: 0
  PODMAN_VER: v4.1.1

jobs:
  build-fetchit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        run: sudo apt install curl
      
      - name: Build the image
        run: go mod tidy -compat=1.17 && go mod vendor && docker build . --file Dockerfile --tag quay.io/fetchit/fetchit-amd:latest
    
      - name: Export image
        run: docker save -o /tmp/fetchit.tar quay.io/fetchit/fetchit-amd:latest

      - name: Save container as artifact
        uses: actions/upload-artifact@v1
        with:
          name: fetchit-image
          path: /tmp/fetchit.tar

  build-ansible-amd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: go mod tidy -compat=1.17 && go mod vendor && make build-ansible-cross-build-linux-amd64

      - name: docker list images
        run: docker images

      - name: Export image
        run: podman save -o /tmp/ansible-amd.tar quay.io/fetchit/fetchit-ansible-amd:latest

      - name: Save container as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ansible-image-amd
          path: /tmp/ansible-amd.tar

  build-systemd-amd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: go mod tidy -compat=1.17 && go mod vendor && make build-systemd-cross-build-linux-amd64

      - name: docker list images
        run: docker images

      - name: Export image
        run: podman save -o /tmp/systemd-amd.tar quay.io/fetchit/fetchit-systemd-amd:latest

      - name: Save container as artifact
        uses: actions/upload-artifact@v1
        with:
          name: systemd-image-amd
          path: /tmp/systemd-amd.tar

  scan-fetchit-sbom:
    runs-on: ubuntu-latest
    needs: [build-fetchit]
    steps:
      - name: Download fetchit image
        uses: actions/download-artifact@v1
        with:
          name: fetchit-image
          path: /tmp

      - name: load images
        run: podman load -i /tmp/fetchit.tar

      - name: Run Trivy vulnerability scanner against FetchIt
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: quay.io/fetchit/fetchit-amd:latest
          format: 'github'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  scan-systemd:
    runs-on: ubuntu-latest
    needs: [build-systemd-amd]
    steps:
      - name: Download systemd image
        uses: actions/download-artifact@v1
        with:
          name: systemd-image-amd
          path: /tmp

      - name: load images
        run: podman load -i /tmp/systemd-amd.tar

      - name: Run Trivy vulnerability scanner against systemd
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: quay.io/fetchit/fetchit-systemd-amd:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  scan-ansible:
    runs-on: ubuntu-latest
    needs: [build-ansible-amd]
    steps:
      - name: Download ansible image
        uses: actions/download-artifact@v1
        with:
          name: ansible-image-amd
          path: /tmp

      - name: load images
        run: podman load -i /tmp/ansible-amd.tar

      - name: Run Trivy vulnerability scanner against ansible
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: quay.io/fetchit/fetchit-ansible-amd:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'