# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: podman version && loginctl enable-linger $(whoami) && echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
        
      - name: systemctl
        run: sudo systemctl enable --now podman.socket

      - name: run harpoon
        run: sudo podman run -d --name harpoon -v ./examples/config.json:/opt/config.json -v /run/podman/podman.sock:/run/podman/podman.sock quay.io/harpoon/harpoon:latest
        
      - name: sleep 1m
        run: sleep 1m
        
      - name: podman list
        run: sudo podman ps
